### ISSUE TITLE
Will there be a docToolchain/aoc-2021

### ISSUE THREAD

**Issue by anoff** [docToolchain/aoc-2021#1]
Are you already preparing something?
Need some help?

**Comment by anoff** [comment]
haha just wanted to add codespaces but you beat me to it again..

**Comment by rdmueller** [comment]
:-) already added it to another repo, so that move was easy... but the container definition is the one from last year. Hope it is still ok.

**Comment by anoff** [comment]
Do you want to keep gitpod docs in there or should we switch completely to codespaces?

**Comment by rdmueller** [comment]
good question. I thought we can have both. codepasces needs AFAIK docker up and running. Not everybody meets these requirements.

**Comment by anoff** [comment]
let's get this going! Thanks Ralf!
